services:
  # Backend Web Service
  - type: web
    name: shortlink-backend
    env: node
    plan: free
    rootCommand: cd backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        sync: false # Render will ask you to input this value
      - key: DATABASE_URL
        fromDatabase:
          name: shortlink-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: USE_HTTPS
        value: true
      # Add your Cloud Storage & SMTP keys manually in Render Dashboard

databases:
  - name: shortlink-db
    plan: free
    databaseName: shortlinkqr
    user: shortlink_user